parameters:

  meta.config:
    title:   'Dungeon Crawler'
    charset: 'utf-8'

    app:
      name_short: 'DC'
      name_full: 'Dungeon Crawler'

    description: 'This application is a Dungeon Crawler'
    keywords:    'eureka, web, application, template, component, php, framework'
    author:      'Romain Cottard'
    version:     '%app.version%'

    copyright:
      year: 'now'
      name: 'velkuns'

    footer:
      links: [ ]

    #~ Other meta data

    social:
      facebook: '#'
      twitter: 'https://twitter.com/velkuns'
      feed: '#'
