# Services Yaml file
parameters:
    app.name:    'eureka'
    app.version: '0.0.1'

services:

    ####################################################################################################################
    # Symfony Container
    ####################################################################################################################
    Symfony\Component\DependencyInjection\ContainerInterface:
        alias: 'service_container'

    Psr\Container\ContainerInterface:
        alias: 'service_container'
